
Vagrant.configure("2") do |config|
    # M1 mac
    config.vm.box = "jeffnoxon/ubuntu-20.04-arm64"

    # sleep 30 before running ansible provisioner
    config.vm.provision "shell", inline: "sleep 30"

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../complex/ansible/playbook.yaml"
      ansible.config_file = "../complex/ansible/ansible.cfg"
    end
  end
