- name: Download the cloudflared Linux package
  ansible.builtin.shell: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

- name: Depackage cloudflared
  ansible.builtin.shell: sudo dpkg -i cloudflared-linux-amd64.deb

- name: Create a cloudflared service directory
  ansible.builtin.shell: mkdir -p /etc/cloudflared/

- name: Create the config file for cloudflared and define the ingress rules for the tunnel
  ansible.builtin.copy:
    dest: "/etc/cloudflared/config.yml"
    content: |
      tunnel: "{{ tunnel_id }}"
      credentials-file: /etc/cloudflared/cert.json
      logfile: /var/log/cloudflared.log
      loglevel: info
      ingress:
        - hostname: "ip-addr.{{ zone }}"
          service: http://localhost:80
        - service: http_status:404

- name: Create the tunnel credentials file for cloudflared
  ansible.builtin.copy:
    dest: "/etc/cloudflared/cert.json"
    content: |
      {
        "AccountTag"   : "{{ account | quote }}",
        "TunnelID"     : "{{ tunnel_id | quote }}",
        "TunnelName"   : "{{ tunnel_name | quote }}",
        "TunnelSecret" : "{{ secret | quote }}"
      }

- name: Install the tunnel as a systemd service
  ansible.builtin.shell: cloudflared service install

- name: Start the tunnel
  ansible.builtin.systemd:
    name: cloudflared
    state: started
    enabled: true
    masked: false
