- name: Install and configure ip addr app
  hosts: all
  become: true

  vars:
    server_name: "127.0.0.1" # use 127.0.0.1 if not using cloudflare or a domain
    git_enabled: false # set to false if not using git to pull the repo; files will be copied instead
    cf_enabled: false # set to false if not using cloudflare

  # vars_files:
  #   - git_vars.yaml # comment out if not using git
  #   - cf_vars.yaml # comment out if not using cloudflare

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  tasks:
    - name: Include git tasks
      ansible.builtin.import_tasks: git.yaml
      when: git_enabled | default(false)

    - name: Include ip addr tasks
      ansible.builtin.import_tasks: ip_addr.yaml

    # comment out if not using cloudflare
    - name: Include cloudflare tunnel tasks
      ansible.builtin.import_tasks: cloudflare.yaml
      when: cf_enabled | default(false)
