repos:
- repo: https://github.com/sourcery-ai/sourcery
  rev: v1.10.0
  hooks:
  - id: sourcery
    # The best way to use Sourcery in a pre-commit hook:
    # * review only changed lines:
    # * omit the summary
    args: [--diff=git diff HEAD, --no-summary]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3.11

-   repo: local
    hooks:
    - id: empty file contents
      name: empty file contents
      entry: ./scripts/empty_file_contents.sh
      language: script
      files: app.json

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7
    hooks:
    -   id: ripsecrets-system
