repos:
- repo: https://github.com/sourcery-ai/sourcery
  rev: v1.2.0
  hooks:
  - id: sourcery
    # The best way to use Sourcery in a pre-commit hook:
    # * review only changed lines:
    # * omit the summary
    args: [--diff=git diff HEAD, --no-summary]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.11
