version: "3"
services:
  ip-addr-challenge:
    # build: .
    # image: timmyb824/ip-addr-challenge:latest-arm64v8
    image: timmyb824/ip-addr-challenge:latest
    container_name: ip-addr-challenge
    # ports:
    #   - "5001:5001"
    restart: always
    # overrides the command in the Dockerfile if needed
    # command: gunicorn src.main:app -w 2 --threads 2 -b 0.0.0.0:5001
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.ip-addr-challenge.rule: Host(`ip-addr.timmybtech.com`)
      traefik.http.services.ip-addr-challenge.loadbalancer.server.port: 5001


  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - ip-addr-challenge

  traefik-app:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt/live/ip-addr.timmybtech.com/fullchain.pem:/etc/traefik/cert.pem:ro
      - /etc/letsencrypt/live/ip-addr.timmybtech.com/privkey.pem:/etc/traefik/privkey.pem:ro
      - ./configs/traefik_dynamic.yaml:/etc/traefik/dynamic.yaml:ro
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --metrics.prometheus=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443

networks:
  default:
    name: traefik
    external: true
