
Vagrant.configure("2") do |config|
    # M1 mac
    config.vm.box = "jeffnoxon/ubuntu-20.04-arm64"

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./server.yaml"
      # ansible.config_file = "./ansible.cfg"
    end
  end

