- name: Install and configure ip-addr app
  hosts: all
  become: true

  vars:
    git_enabled: false # set to false if not using git to pull the repo; files will be copied instead
    cf_enabled: false # set to true if using cloudflare tunnels
    nginx_enabled: false
    cf_ddns_enabled: false
    tailscale_enabled: false
    docker_enabled: false
    loki_docker_enabled: false
    certbot_enabled: false

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    # https://github.com/artis3n/ansible-role-tailscale
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') }}"
        # tailscale_args: "--accept-routes" # use on linux to access subnet routing
      when: tailscale_enabled | default(false)

    # https://github.com/geerlingguy/ansible-role-docker
    # docker_daemon_json did not work with this role
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_user }}"
      when: docker_enabled | default(false)

  tasks:
    - name: Include loki_docker logging tasks
      ansible.builtin.import_tasks: tasks/loki_docker.yaml
      when: loki_docker_enabled | default(false)

    - name: Include git tasks
      ansible.builtin.import_tasks: tasks/git.yaml
      when: git_enabled | default(false)

    - name: Include ip addr tasks
      ansible.builtin.import_tasks: tasks/ip_addr.yaml

    - name: Include cloudflare tunnel tasks
      ansible.builtin.import_tasks: tasks/cloudflare.yaml
      when: cf_enabled | default(false)

    - name: Include install cloudflare-ddns tasks
      ansible.builtin.import_tasks: tasks/cf_ddns.yaml
      when: cf_ddns_enabled | default(false)

    - name: Include install certbot tasks
      ansible.builtin.import_tasks: tasks/certbot.yaml
      when: certbot_enabled | default(false)

    - name: Include nginx tasks
      ansible.builtin.import_tasks: tasks/nginx.yaml
      when: nginx_enabled | default(false)
