- name: Install and configure ip-addr app
  hosts: all
  become: true

  vars:
    git_enabled: true # set to false if not using git to pull the repo; files will be copied instead
    cf_enabled: false # set to true if using cloudflare tunnels
    ipaddr_enabled: true
    cf_ddns_enabled: false
    tailscale_enabled: true
    docker_enabled: false
    loki_docker_enabled: false
    nginx_certbot_enabled: true
    zabbix_enabled: false
    promtail_enabled: false
    firewalld_enabled: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.import_tasks: tasks/update_pkgs.yaml

  roles:
    # https://github.com/artis3n/ansible-role-tailscale
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') }}"
        tailscale_args: "--accept-routes" # use on linux to access subnet routing
      when: tailscale_enabled | default(false)

    # https://github.com/geerlingguy/ansible-role-docker
    # docker_daemon_json did not work with this role
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_user }}"
      when: docker_enabled | default(false)

  tasks:
    - name: Include loki_docker logging tasks
      ansible.builtin.import_tasks: tasks/loki_docker.yaml
      when: loki_docker_enabled | default(false)

    - name: Include git tasks
      ansible.builtin.import_tasks: tasks/git.yaml
      when: git_enabled | default(false)

    - name: Include ip addr tasks
      ansible.builtin.import_tasks: tasks/ip_addr.yaml
      when: ipaddr_enabled | default(false)

    - name: Include firewalld tasks
      ansible.builtin.import_tasks: tasks/firewalld.yaml
      when: firewalld_enabled | default(false)

    - name: Include cloudflare tunnel tasks
      ansible.builtin.import_tasks: tasks/cloudflare.yaml
      when: cf_enabled | default(false)

    - name: Include cloudflare-ddns tasks
      ansible.builtin.import_tasks: tasks/cf_ddns.yaml
      when: cf_ddns_enabled | default(false)

    - name: Include nginx_certbot tasks
      ansible.builtin.import_tasks: tasks/nginx_certbot.yaml
      when: nginx_certbot_enabled | default(false)

    - name: Include zabbix tasks
      ansible.builtin.import_tasks: tasks/zabbix_agent2.yaml
      when: zabbix_enabled | default(false)

    - name: Include promtail tasks
      ansible.builtin.import_tasks: tasks/promtail.yaml
      when: promtail_enabled | default(false)
