## This configuration was generated by terraform-provider-oci

resource "oci_core_network_security_group" "ipaddr-NSG" {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/timothybryant3@gmail.com"
  }
  display_name = "ipaddr-NSG"
  freeform_tags = {
  }
  vcn_id = var.vcn_ocid
}

resource "oci_core_network_security_group_security_rule" "ipaddr-NSG_network_security_group_security_rule" {
  #description = <<Optional value not found in discovery>>
  destination               = "0.0.0.0/0"
  destination_type          = "CIDR_BLOCK"
  direction                 = "EGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "all"
  #source = <<Optional value not found in discovery>>
  source_type = ""
  stateless   = "false"
}

resource "oci_core_network_security_group_security_rule" "ipaddr-NSG_network_security_group_security_rule_1" {
  #description = <<Optional value not found in discovery>>
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "22"
      min = "22"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource "oci_core_network_security_group_security_rule" "homelab-igNSG_network_security_group_security_rule_2" {
  description = "ipaddr-app"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "5001"
      min = "5001"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource "oci_core_network_security_group_security_rule" "homelab-igNSG_network_security_group_security_rule_4" {
  description = "http"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "80"
      min = "80"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource "oci_core_network_security_group_security_rule" "homelab-igNSG_network_security_group_security_rule_5" {
  description = "https"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "443"
      min = "443"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource "oci_core_network_security_group_security_rule" "homelab-igNSG_network_security_group_security_rule_6" {
  description = "zabbix"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "10051"
      min = "10050"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource "oci_core_network_security_group_security_rule" "homelab-igNSG_network_security_group_security_rule_7" {
  description = "promtail"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.ipaddr-NSG.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "9080"
      min = "9080"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}
