tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/letsencrypt/live/ip-addr.timmybtech.com/fullchain.pem
        keyFile: /etc/traefik/letsencrypt/live/ip-addr.timmybtech.com/privkey.pem
