- name: Include vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/vars/certbot_vars.yaml"

- name: Install NGINX
  ansible.builtin.apt:
    name:
      - nginx
    state: present

- name: Ensure latest version of snapd (install)
  ansible.builtin.command: snap install core

- name: Ensure latest version of snapd (refresh)
  ansible.builtin.command: snap refresh core

- name: Install certbot with snap
  community.general.snap:
    name: certbot
    classic: true

- name: Symlink certbot to /usr/bin
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

# --resuse-key is used to prevent rate limiting (e.g. --cert-path /etc/letsencrypt/live/example.com/privkey.pem --reuse-key)
# will need to save the private key somewhere to reuse it
- name: Configure Certbot
  ansible.builtin.command: certbot certonly --nginx -d {{ server_name }} --agree-tos --email {{ email }} --non-interactive --no-eff-email
  args:
    creates: /etc/letsencrypt/live/{{ server_name }}/fullchain.pem

- name: Test automatic renewal
  ansible.builtin.command: certbot renew --dry-run
  register: certbot_renewal
  ignore_errors: true

# output the result of the renewal test
- ansible.builtin.debug: var=certbot_renewal
- ansible.builtin.debug: msg="{{ certbot_renewal.stdout }}"
