- name: Install Python3, pip, and NGINX
  ansible.builtin.apt:
    name: ['python3', 'python3-pip']
    state: present

- name: Install python requirements
  ansible.builtin.pip:
    requirements: requirements.txt
    chdir: /home/{{ ansible_user }}/ip-addr/

- name: Copy systemd unit file
  ansible.builtin.template:
    src: '{{ playbook_dir }}/templates/ip-addr.service.j2'
    dest: /etc/systemd/system/ip-addr.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start ip-addr service
  ansible.builtin.systemd:
    name: ip-addr.service
    state: started
    enabled: true
