- name: Include vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/vars/nginx_vars.yaml"

# Installed during certbot tasks
# - name: Install NGINX
#   ansible.builtin.apt:
#     name:
#       - nginx
#     state: present

- name: Copy NGINX configuration file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/ssl_nginx.conf.j2"
    dest: /etc/nginx/sites-available/ip-addr.conf
    mode: '0644'

- name: Enable NGINX configuration file
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ip-addr.conf
    dest: /etc/nginx/sites-enabled/ip-addr.conf
    state: link

- name: Disable default NGINX configuration file
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test NGINX configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  ignore_errors: true

- name: Restart NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_test.rc == 0
