---
- name: Update apt packages
  become: true
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: true
    cache_valid_time: 86400 # One day
  when:
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Update yum packages
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: true
  when:
    - ansible_distribution == "Amazon"
