name: build and test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment:
      name: testing
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v3

      - name: install python version 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: update pip
        shell: bash
        run: python -m pip install --upgrade pip

      - name: install all dependencies
        shell: bash
        run: pip install -r requirements.txt

      - name: test with pytest
        shell: bash
        run: |
          pip install pytest
          pytest -xv
