name: Deploy to Cloud Provider

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_KEY }}
          passphrase: ${{ secrets.OCI_PASSPHRASE }}
          port: ${{ secrets.OCI_PORT }}
          script: |
            cd /home/ubuntu/ip-addr
            git pull
            sudo systemctl restart ip-addr.service
